export default {
  Base: "/api",
  Users: {
    Base: "/users",
    Get: "/all",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
    Detail: "/:id",
    Search: "/",
    ChangeStatus: "/changeStatus/:id",
    UpdateChat: "/update-chat/:chatId",
  },
  Auth: {
    Base: "/auth",
    SignUp: "/sign-up",
  },
  HousingAreas: {
    Base: "/housing-areas",
    Add: "/add",
    UpdatePending: "/update-pending/:housingAreaId",
    RejectAdd: "/reject/:housingAreaId",
    ApproveAdd: "/approve/:housingAreaId",
    ReSubmit: "/resubmit/:housingAreaId",
    UserPublish: "/user-publish/:housingAreaId",
    UserUnpublish: "/user-unpublish/:housingAreaId",
    AdminPublish: "/admin-publish/:housingAreaId",
    AdminUnpublish: "/admin-unpublish/:housingAreaId",
    GetDetail: "/detail/:housingAreaId",
    ApproveUpdate: "/approve-update/:housingAreaId",
    RejectUpdate: "/reject-update/:housingAreaId",
    Delete: "/delete/:housingAreaId",
    GetListByUserId: "/by-user",
    AddRate: "/add-rate/:housingAreaId",
    ChangeRateStatus: "/change-rate-status/:housingAreaId/:id",
    GetRateList: "/rate-list/:housingAreaId",
    UpdateAdmin: "/update-admin/:housingAreaId",
    DeleteAdmin: "/delete-admin/:housingAreaId",
    Search: "/search",
  },
  Rooms: {
    Base: "/rooms",
    AddMany: "/add-many",
    Update: "/update/:roomId",
    Search: "/search",
    GetListByHousingAreaId: "/by-housing-area/:housingAreaId",
    Delete: "/delete/:roomId",
    GetDetail: "/detail/:roomId",
    GetBoostingRooms: "/get-boosting-rooms",
    AddSavedRoom: "/add-saved-room/:roomId",
    GetListSavedRooms: "/get-list-saved-rooms",
    DeleteRoomSaved: "/delete-room-saved/:roomId",
  },
  Transactions: {
    Base: "/transactions",
    Add: "/add",
    History: "/history",
    All: "/all",
  },
  ZaloPay: {
    Base: "/zalo-pay",
    AgreementBind: "/agreement-bind",
    CreateOrder: "/create-order",
    CreateOrderCallback: "/create-order/callback",
    QueryOrder: "/query-order",
    CreateRefund: "/create-refund",
    QueryRefund: "/query-refund",
  },
  Contracts: {
    Base: "/contracts",
    Add: "/add/:roomId",
    GetByTenant: "/get-by-tenant",
    GetByOwner: "/get-by-owner",
    GetById: "/get-by-id/:contractId",
    SignByLandlord: "/sign-by-landlord/:contractId",
    UpdateDepositStatus: "/update-deposit-status/:contractId",
    RequestExtension: "/request-extension/:contractId",
    ConfirmExtension: "/confirm-extension/:contractId",
  },
  Disputes: {
    Base: "/disputes",
    Add: "/add",
    GetByContractId: "/get-by-contract/:contractId",
    GetByUserId: "/get-by-user/",
    Resolve: "/resolve/:disputeId",
    Detail: "/detail/:disputeId",
    GetListSearch: "/get-list-search",
    AdminHandleDesicion: "/admin-handle-decision/:disputeId",
  },
  Admin: {
    Base: "/admin",
    Statistics: {
      Base: "/statistics/housing-area",
      Overview: "/statistics/housing-area/overview",
      BoostRevenue: "/statistics/boost-revenue",
      PostingRevenue: "/statistics/posting-revenue",
      PostingRevenueOverview: "/statistics/posting-revenue/overview",
    },
  },
} as const;
